name: oholiab
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  meta: ^1.2.4

dev_dependencies:
  test: ^1.14.4
  build_runner: ^1.9.0
  build_test: ^1.0.0
  build_web_compilers: ^2.10.0
  pedantic: ^1.9.0
